image: mrcyjanek/testportal-multitool:latest
script:
 - web-ext sign --api-key="$WEB_EXT_API_KEY" --api-secret="$WEB_EXT_API_SECRET" --channel=unlisted
 - cp $(find . -name "*.xpi") /archive/testportal-multitool-edge.xpi 
